### PR TITLE
[Fix] Webhook filtering when batching is enabled

### PR DESCRIPTION
**Pull request by Daynnnnn**
Runs a filter on the events array, then makes sure the events array isn't empty before generating the signature and sending the webhook

### CODE REVIEW

**Comment by rennokki** [comment]
If I remember correctly, this issue is caused by the fact that the signature is indeed made before it hits the jobs processor (can be local or Redis, etc.).

The app especially sends the job with the signature instead of the app secret due to security reasons. In case Redis gets broken into, the attackers can see the app secret, which is attached to the job. In case they can generate other payloads as well without knowing. An attacker who has access to Redis can only see the signature, which can be made public.

This also adds another issue: the issue your PR tries to solve. 😁

The signature somehow needs to be recalculated, OR **checked against the original payload BEFORE filtering**.

Hope this helps. 😁

**Comment by Daynnnnn** [comment]
Ahhhh I see, so the fact that the signature was generated before the queue meant that the payload couldn't be tampered with. But this new method means means the signature doesn't get generated until the job is being executed, meaning payloads can be tampered/added in redis.

What the flow actually needs to be is:
- We calculate the signature and push that as part of the job to the queue, the same way we did before.
- When the job runs, before filtration, we should make sure the signature still matches the payload. This ensures the payload hasn't been tampered with in redis.
- We then do the filtration, and if any events get filtered out, we regenerate the signature.

I'll work on that now, that's for the feedback 😄

**Comment by rennokki** [comment]
Wonderful ❤️

**Comment by liverocaisson** [comment]
The webhook on member_removed event seems to not working since this patch.

https://github.com/soketi/soketi/issues/502

**Pull request merged**
