### PR TITLE
[fix] Integer values for `app_id` cause communication issues

### LINKED ISSUE #10: How to implement support for Redis Sentinel?
As I've written on Reddit already, it would be nice to have support for Redis Sentinel. But before we dig into details, a bit of background about what Redis Sentinel is:
> Redis Sentinel provides high availability for Redis. In practical terms this means that using Sentinel you can create a Redis deployment that resists without human intervention certain kinds of failures.
> 
> Redis Sentinel also provides other collateral tasks such as monitoring, notifications and acts as a configuration provider for clients.
> 
> This is the full list of Sentinel capabilities at a macroscopical level (i.e. the big picture):
> - Monitoring. Sentinel constantly checks if your master and replica instances are working as expected.
> - Notification. Sentinel can notify the system administrator, or other computer programs, via an API, that something is wrong with one of the monitored Redis instances.
> - Automatic failover. If a master is not working as expected, Sentinel can start a failover process where a replica is promoted to master, the other additional replicas are reconfigured to use the new master, and the applications using the Redis server are informed about the new address to use when connecting.
> - Configuration provider. Sentinel acts as a source of authority for clients service discovery: clients connect to Sentinels in order to ask for the address of the current Redis master responsible for a given service. If a failover occurs, Sentinels will report the new address.

In other words, Redis Sentinel ensures there is always a master available. In a failover scenario, this is ensured by promoting a replica to be the new master.

In terms of "connecting to Redis", we are essentially talking about a proxy which needs to be queried for its current master before we can connect to the actual Redis instance. Luckily, [`ioredis` has this built-in already](https://github.com/luin/ioredis#sentinel).

---

So my questions regarding a potential implementation are:

- Currently, the environment variables are basically the same options which are passed to `ioredis`. Do we want to use the same configuration style for Redis Sentinel as well? It would for sure be nice, but I see two problems here:
  - `ioredis` allows configuring multiple Sentinels, which seems hard/cumbersome to implement with statically mapped environment variables (`DB_REDIS_SENTINEL_0_HOST`, `DB_REDIS_SENTINEL_1_HOST`, ...).

  - There would be room for interpretation if both options (non-sentinel and sentinel) are configured. And if both were made optional, it would be a breaking change in my opinion.

- Would it be ok to have a `DB_REDIS_SENTINEL=true/false` setting to allow switching to Sentinel mode? We could then simply use a different connection configuration internally, based on the already existing environment variables `DB_REDIS_HOST` and `DB_REDIS_PORT`. This would not allow defining multiple Sentinels though. In my case, this is not an issue, because we are connecting to the Sentinels through a Kubernetes Service and a short outage of a few seconds is acceptable (and better for us than a complex configuration).

- Would it be ok to have a `DB_REDIS_URLS` option which allows to pass multiple `host:port` combinations in a comma separated fashion (`DB_REDIS_URLS=localhost:6379,localhost:6380`)? This solves some of the problems and introduces new ones (e.g. precedence of configuration options).

I think it is better to discuss this before starting an implementation. Eager to hear your feedback on this ideas!

### PR DESCRIPTION
**Pull request by mattoz0**
This one fixes the possibility of the server reading the APP_ID as an int. It's got a test that covers it also.

Closes #10

### CODE REVIEW

**Comment by rennokki** [comment]
I have skipped this PR because it's highly encouraged to use strings for IDs.

**Comment by mattoz0** [comment]
@rennokki 
Firstly we migrated from Pusher and were reusing our APP_ID directly from them. So this case will pop up quite regularly.

The problem is not that the field is a string, the problem is when your application is loading the APP_ID its interpreting it as an Integer if its a number. So your silently sending the communication to another channel, anyway you slice that its a bug.

If you don't accept this PR, you should replace it with an error message. Currently it just fails silently with no obvious reason. For first time users of the package this will take a long time of debugging to figure out. I know it took me two weeks to figure out and, even after i fixed it the first time i didn't know what had changed.

[Doco + error Message] or [Fix] is my opinion.

**Comment by rennokki** [comment]
You are right about this one. Can you sync it with `master`?

**Comment by mattoz0** [comment]
Yeah no worries, ill get it done now!

**Comment by mattoz0** [comment]
Just noticed the new test i added is failing in some configurations! Ill spend some time over the weekend looking into it!

**Comment by rennokki** [comment]
@mattoz0 Don't worry, had some stuff to figure out in the meanwhile. I'll fix the test, it seems like the checks should be only for the `array` driver.

**Pull request merged**
