### PR TITLE
[fix] Debian Docker builds

### LINKED ISSUE #449: Docker images not working as expected with SSL
We have just updated our docker images, we were stuck on the `soketi/pws` images for a while. After taking a look a the newer images located at `quay.io/soketi/soketi` i have noticed two issues.

1. The images that are post-fixed with `-alpine` seem to have a segmentation fault and don't work at all. The seg fault happens as soon as you try to connect to the echo server from a frontend application.

```
echo  |   📡 soketi initialization....
echo  |   ⚡ Initializing the HTTP API & Websockets Server...
echo  |   ⚡ Initializing the Websocket listeners and channels...
echo  |   ⚡ Initializing the HTTP webserver...
echo  |   🕵️‍♂️ Initiating metrics endpoints...
echo  |
echo  |    🎉 Server is up and running!
echo  |    📡 The Websockets server is available at 127.0.0.1:6001
echo  |    🔗 The HTTP API server is available at http://127.0.0.1:6001
echo  |    🎊 The /usage endpoint is available on port 9601.
echo  |
echo  |    [Fri Apr 08 2022 04:30:25 GMT+0000 (Coordinated Universal Time)] Promoted from node to master.
echo  |   [object Object]
echo exited with code 139
```

2. The images that are post-fixed with `-distroless` seem to no longer be generating since about 2 months ago (last one was `0.30.2-16-distroless`). Its worth noting these images are recommended for production in the documentation. here: https://docs.soketi.app/getting-started/installation/docker

I have confirmed that the distroless images do not have the seg fault and work fine. I have also confirmed the seg fault was not present in the older `soketi/pws` images.

### PR DESCRIPTION
**Pull request by rennokki**
- Added Debian builds
- Grouped docker builds in same files

Closes #449

### CODE REVIEW

**Comment by rennokki** [comment]
@mattoz0 Please let me know if this build is working for you (it's the latest 0.x): ` 5c6f5e8ec0b20bd2b1c88ee552ee14d72e5c31dc-16-debian`

What concerns me and delayed me merging this to 0.x is the fact that the image has active CVEs: https://quay.io/repository/soketi/soketi/manifest/sha256:0943879cbb228edaf5dfd468cf0bcfd0906e50167a047c4f51960fc41fec869f?tab=vulnerabilities

**Comment by mattoz0** [comment]
I've tested the image and confirm it doesn't throw a Segmentation fault which makes it a much better candidate than the alpine images. 

Not sure about the CVE's, i'll have a look tonight to see if there is some magical command we can run and fix most of them.

**Comment by rennokki** [comment]
Not sure if `apt-get update` would fix the things, but I think it's the first thing that needs to be done. 😓

**Comment by rennokki** [comment]
@mattoz0 I think it's more of a scanner issue rather than actual CVEs.

1. If you look at the [CVE list](https://quay.io/repository/soketi/soketi/manifest/sha256:0943879cbb228edaf5dfd468cf0bcfd0906e50167a047c4f51960fc41fec869f?tab=vulnerabilities), in the `FIXED IN VERSION` column, none of them have versions in which this is fixed. 
2. See https://github.com/nodejs/docker-node/issues/1677#issuecomment-1073699535 and the immediate reply.

**Comment by mattoz0** [comment]
It does seems strange that debian images have far more CVE's. I found this issue https://github.com/quay/clair/issues/1270#issuecomment-953727912 which seems to suggest that any of the Debian `fixed in 0:0` are actually issues but not affecting the current version. 

I think this is just a bug in the security scanner for sure, i wouldn't be surprised if this ones already fixed waiting on a release.

**Pull request merged**
